name: "code build and deploy"

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2

      - name: Dockerversion
        run: docker --version
      - name: All files
        run: ls
      - name: PWD
        run: pwd
      
